fail_fast: false
default_language_version:
    python: python3
default_stages:
    - commit
minimum_pre_commit_version: 2.19.0
repos:
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.950
        hooks:
        -   id: mypy

    -   repo: https://github.com/pycqa/flake8
        rev: ''
        hooks:
        -   id: flake8

    -   repo: https://github.com/asottile/pyupgrade
        rev: v2.32.1
        hooks:
        -   id: pyupgrade

    -   repo: https://github.com/asottile/reorder_python_imports
        rev: v3.1.0
        hooks:
        -   id: reorder-python-imports

    -   repo: https://github.com/asottile/yesqa
        rev: v1.3.0
        hooks:
        -   id: yesqa