version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./:/usr/stat_inc/
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0.6
    restart: always
    expose:
      - 27017
