version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./:/usr/stat_inc/
    depends_on:
      - mongo
    networks:
      - my-proxy-net
    labels:
      - traefik.enable=true
      - traefik.http.services.web.loadbalancer.server.port=8001
      - traefik.http.routers.web.entrypoints=http
      - traefik.http.routers.web.rule=PathPrefix("/api/gateway") || PathPrefix("/db") || PathPrefix("/auth")
      - traefik.docker.network=stat_inc_network

  mongo:
    image: mongo:5.0.6
    restart: always
    expose:
      - 27017
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    external:
      name: stat_inc_network
